import path from 'path'
import fs from 'fs-extra'
import { FileRef, nextTestSetup } from 'e2e-utils'
import { retry } from 'next-test-utils'

const exampleDir = path.join(
  __dirname,
  '..',
  '..',
  '..',
  'examples',
  'with-msw'
)
const examplePackageJson = fs.readJsonSync(
  path.join(exampleDir, 'package.json')
)

describe('examples/with-msw', () => {
  const { next } = nextTestSetup({
    files: {
      // The mock bootstrap of the example is what is under test here.
      mocks: new FileRef(path.join(exampleDir, 'mocks')),
      'pages/_app.tsx': new FileRef(path.join(exampleDir, 'pages', '_app.tsx')),
      '.env.development': new FileRef(
        path.join(exampleDir, '.env.development')
      ),
      'tsconfig.json': new FileRef(path.join(exampleDir, 'tsconfig.json')),
      // A page that requests a mocked endpoint on its first client render.
      'pages/index.tsx': new FileRef(
        path.join(__dirname, 'fixture-pages', 'index.tsx')
      ),
    },
    dependencies: {
      msw: examplePackageJson.dependencies.msw,
    },
  })

  beforeAll(async () => {
    // `public/mockServiceWorker.js` is generated by `msw init` and therefore
    // git-ignored in the example, so seed it from the installed msw package.
    const workerScript = await fs.readFile(
      require.resolve('msw/mockServiceWorker.js', { paths: [next.testDir] }),
      'utf8'
    )
    await next.patchFile('public/mockServiceWorker.js', workerScript)
    await retry(async () => {
      const res = await next.fetch('/mockServiceWorker.js')
      expect(res.status).toBe(200)
    }, 30_000)
  })

  it('mocks a request made on the initial client render', async () => {
    const browser = await next.browser('/')

    await retry(async () => {
      const result = await browser.elementByCss('#result').text()
      expect(result).not.toBe('pending')
    }, 30_000)

    expect(await browser.elementByCss('#result').text()).toBe(
      'mocked John Maverick'
    )
  })
})
