import { chromium } from 'playwright';
const base = process.argv[2] || 'http://localhost:3000';
const tag = process.argv[3] || 'dev';
const out = process.env.OUT_DIR || '.';
const b = await chromium.launch(process.env.CHROME_PATH ? { executablePath: process.env.CHROME_PATH } : {});
const p = await b.newPage();
const color = async () => p.$eval('#square', el => getComputedStyle(el).backgroundColor);
const links = async () => p.$$eval('link[rel=stylesheet],style', els => els.map(e => e.tagName + ':' + (e.getAttribute('href')||'inline')));
await p.goto(base + '/', { waitUntil: 'networkidle' });
console.log('1. initial home (expect blue rgb(0,0,255)):', await color());
await p.screenshot({ path: `${out}/${tag}-1-home-initial.png` });
await p.click('#to-other');
await p.waitForSelector('#to-home');
await p.waitForTimeout(500);
console.log('2. /other after nav (expect red rgb(255,0,0)):', await color());
await p.screenshot({ path: `${out}/${tag}-2-other.png` });
await p.click('#to-home');
await p.waitForSelector('#to-other');
await p.waitForTimeout(500);
console.log('3. home after back-nav (expect blue):', await color());
console.log('   stylesheet order:', (await links()).join(' | '));
await p.screenshot({ path: `${out}/${tag}-3-home-after-nav.png` });
await p.reload({ waitUntil: 'networkidle' });
console.log('4. home after hard reload (expect blue):', await color());
await b.close();
