// Generates components/Icon.tsx: an object of 40 icon components,
// each carrying ~4kB of unique path data so tree shaking is measurable.
import { writeFileSync } from 'node:fs'

const NAMES = Array.from({ length: 40 }, (_, i) => `ICON_${i + 1}`)
const pathData = (i) =>
  Array.from({ length: 200 }, (_, j) => `l${i}.${j}${j % 7} ${j}.${i}${j % 5}`).join('')

const body = NAMES.map(
  (name, i) => `  ${name}: (props: IconProps) => (
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 50 50" {...props}>
      <path d="M0 0${pathData(i)}z" />
    </svg>
  ),`
).join('\n')

writeFileSync(
  new URL('./components/Icon.tsx', import.meta.url),
  `// generated by generate-icons.mjs
type IconProps = React.SVGProps<SVGSVGElement>

export const Icon = {
${body}
}
`
)
