#!/usr/bin/env bash
# Reproduction for vercel/next.js#77679
# create-next-app should emit pre-sorted dependencies/devDependencies so that a
# subsequent `pnpm add` does not reorder package.json.
#
# Usage: ./repro.sh <create-next-app-version>   (default: latest)
set -euo pipefail
VERSION="${1:-latest}"
DIR="$(mktemp -d)/app-$VERSION"

npx --yes "create-next-app@$VERSION" "$DIR" \
  --ts --tailwind --eslint --app --src-dir --use-pnpm --no-import-alias --skip-install --yes

cd "$DIR"
echo "=== package.json generated by create-next-app@$VERSION ==="
node -e "const p=require('./package.json');console.log('dependencies   :',Object.keys(p.dependencies).join(', '));console.log('devDependencies:',Object.keys(p.devDependencies).join(', '))"

git init -q && git add -A && git -c user.email=r@r -c user.name=r commit -qm init
pnpm add --lockfile-only @radix-ui/react-popover >/dev/null 2>&1

echo "=== git diff of package.json after \`pnpm add @radix-ui/react-popover\` ==="
git --no-pager diff -- package.json
