#!/usr/bin/env bash
# Reproduces vercel/next.js#89772
# The AGENTS.md block generated by `@next/codemod agents-md` tells the agent:
#   "If docs missing, run this command first: npx @next/codemod agents-md --output AGENTS.md"
# In a clean checkout (dependencies not installed yet) that exact command fails.
set -u
cd "$(dirname "$0")"
echo "--- files present (clean checkout, no node_modules) ---"
ls -a
echo "--- instruction embedded in AGENTS.md ---"
grep -o 'If docs missing[^|]*' AGENTS.md
echo "--- running the embedded command, non-interactive stdin ---"
npx --yes @next/codemod agents-md --output AGENTS.md < /dev/null
echo "EXIT=$?"
