import { chromium } from 'playwright';
const OUT='/workspace/.next-maintainer/reproduction-artifacts/playwright';
const base=process.argv[2]||'http://localhost:3000';
const tag=process.argv[3]||'dev';
const b=await chromium.launch();
const p=await b.newPage();
const nav=[]; 
p.on('framenavigated',f=>{ if(f===p.mainFrame()) nav.push('framenavigated '+f.url()); });
p.on('load',()=>nav.push('load '+p.url()));
p.on('console',m=>nav.push('console['+m.type()+'] '+m.text().slice(0,200)));
const docs=[];
p.on('response',async r=>{ if(r.request().resourceType()==='document') docs.push(r.status()+' '+r.url()); });
await p.goto(base+'/test',{waitUntil:'networkidle'});
nav.push('--- at /test');
await p.getByRole('link',{name:'Go to /test/new'}).click();
await p.waitForURL('**/test/new');
await p.waitForSelector('h2:has-text("new")');
nav.push('--- modal 1 open, url='+p.url());
await p.getByRole('link',{name:'Go to /test/[id]'}).click();
await p.waitForURL('**/test/42');
await p.waitForSelector('h1:has-text("/test/42")');
nav.push('--- at detail, url='+p.url());
await p.screenshot({path:OUT+`/${tag}-1-detail.png`});
await p.getByRole('link',{name:'Go to /test/42/new'}).click();
await p.waitForURL('**/test/42/new');
await p.waitForSelector('text=Update Tag');
nav.push('--- modal 2 open, url='+p.url());
await p.screenshot({path:OUT+`/${tag}-2-modal2.png`});
await p.getByRole('button',{name:'Update Tag'}).click();
await p.waitForTimeout(4000);
nav.push('--- after Update Tag, url='+p.url());
const body=(await p.locator('body').innerText()).slice(0,400);
nav.push('BODY:\n'+body);
await p.screenshot({path:OUT+`/${tag}-3-after-updateTag.png`,fullPage:true});
nav.push('DOCS: '+JSON.stringify(docs,null,1));
console.log(nav.join('\n'));
await b.close();
