import { chromium } from 'playwright';
const base = process.argv[2];
const out = '/workspace/.next-maintainer/reproduction-artifacts/playwright';
const b = await chromium.launch();
const p = await b.newPage();
await p.goto(base + '/');
const before = await p.textContent('#count');
await p.click('#load-more');
await p.waitForFunction(() => document.querySelectorAll('li').length === 20);
const afterLoad = await p.textContent('#count');
await p.screenshot({ path: `${out}/1-after-load-more-${process.argv[3]}.png` });
await p.click('#go-to-10');
await p.waitForSelector('#post-title');
await p.screenshot({ path: `${out}/2-blog-10-${process.argv[3]}.png` });
await p.goBack();
await p.waitForSelector('#count');
await p.waitForTimeout(1500);
const afterBack = await p.textContent('#count');
const liAfterBack = await p.locator('li').count();
await p.screenshot({ path: `${out}/3-after-back-${process.argv[3]}.png` });
console.log(JSON.stringify({ mode: process.argv[3], url: p.url(), before, afterLoad, afterBack, liAfterBack }, null, 2));
await b.close();
