'use client'

import Image from 'next/image'
import icon1 from '../../images/icons/icon1.png'
import icon2 from '../../images/icons/icon2.png'
import icon3 from '../../images/icons/icon3.png'
import icon4 from '../../images/icons/icon4.png'
import icon5 from '../../images/icons/icon5.png'
import icon6 from '../../images/icons/icon6.png'
import icon7 from '../../images/icons/icon7.png'
import icon8 from '../../images/icons/icon8.png'
import icon9 from '../../images/icons/icon9.png'
import icon10 from '../../images/icons/icon10.png'
import icon11 from '../../images/icons/icon11.png'
import icon12 from '../../images/icons/icon12.png'
import icon13 from '../../images/icons/icon13.png'
import icon14 from '../../images/icons/icon14.png'
import icon15 from '../../images/icons/icon15.png'
import icon16 from '../../images/icons/icon16.png'
import icon17 from '../../images/icons/icon17.png'
import icon18 from '../../images/icons/icon18.png'
import icon19 from '../../images/icons/icon19.png'
import icon20 from '../../images/icons/icon20.png'
import icon21 from '../../images/icons/icon21.png'
import icon22 from '../../images/icons/icon22.png'
import icon23 from '../../images/icons/icon23.png'
import icon24 from '../../images/icons/icon24.png'
import icon25 from '../../images/icons/icon25.png'
import icon26 from '../../images/icons/icon26.png'
import icon27 from '../../images/icons/icon27.png'
import icon28 from '../../images/icons/icon28.png'
import icon29 from '../../images/icons/icon29.png'
import icon30 from '../../images/icons/icon30.png'
import icon31 from '../../images/icons/icon31.png'
import icon32 from '../../images/icons/icon32.png'
import icon33 from '../../images/icons/icon33.png'
import icon34 from '../../images/icons/icon34.png'
import icon35 from '../../images/icons/icon35.png'
import icon36 from '../../images/icons/icon36.png'
import icon37 from '../../images/icons/icon37.png'
import icon38 from '../../images/icons/icon38.png'
import icon39 from '../../images/icons/icon39.png'
import icon40 from '../../images/icons/icon40.png'
import icon41 from '../../images/icons/icon41.png'
import icon42 from '../../images/icons/icon42.png'
import icon43 from '../../images/icons/icon43.png'
import icon44 from '../../images/icons/icon44.png'
import icon45 from '../../images/icons/icon45.png'
import icon46 from '../../images/icons/icon46.png'
import icon47 from '../../images/icons/icon47.png'
import icon48 from '../../images/icons/icon48.png'
import icon49 from '../../images/icons/icon49.png'
import icon50 from '../../images/icons/icon50.png'
import icon51 from '../../images/icons/icon51.png'
import icon52 from '../../images/icons/icon52.png'
import icon53 from '../../images/icons/icon53.png'
import icon54 from '../../images/icons/icon54.png'
import icon55 from '../../images/icons/icon55.png'
import icon56 from '../../images/icons/icon56.png'
import icon57 from '../../images/icons/icon57.png'
import icon58 from '../../images/icons/icon58.png'
import icon59 from '../../images/icons/icon59.png'
import icon60 from '../../images/icons/icon60.png'
import icon61 from '../../images/icons/icon61.png'
import icon62 from '../../images/icons/icon62.png'
import icon63 from '../../images/icons/icon63.png'
import icon64 from '../../images/icons/icon64.png'
import icon65 from '../../images/icons/icon65.png'
import icon66 from '../../images/icons/icon66.png'
import icon67 from '../../images/icons/icon67.png'
import icon68 from '../../images/icons/icon68.png'
import icon69 from '../../images/icons/icon69.png'
import icon70 from '../../images/icons/icon70.png'
import icon71 from '../../images/icons/icon71.png'
import icon72 from '../../images/icons/icon72.png'
import icon73 from '../../images/icons/icon73.png'
import icon74 from '../../images/icons/icon74.png'
import icon75 from '../../images/icons/icon75.png'
import icon76 from '../../images/icons/icon76.png'
import icon77 from '../../images/icons/icon77.png'
import icon78 from '../../images/icons/icon78.png'
import icon79 from '../../images/icons/icon79.png'
import icon80 from '../../images/icons/icon80.png'
import icon81 from '../../images/icons/icon81.png'
import icon82 from '../../images/icons/icon82.png'
import icon83 from '../../images/icons/icon83.png'
import icon84 from '../../images/icons/icon84.png'
import icon85 from '../../images/icons/icon85.png'
import icon86 from '../../images/icons/icon86.png'
import icon87 from '../../images/icons/icon87.png'
import icon88 from '../../images/icons/icon88.png'
import icon89 from '../../images/icons/icon89.png'
import icon90 from '../../images/icons/icon90.png'
import icon91 from '../../images/icons/icon91.png'
import icon92 from '../../images/icons/icon92.png'
import icon93 from '../../images/icons/icon93.png'
import icon94 from '../../images/icons/icon94.png'
import icon95 from '../../images/icons/icon95.png'
import icon96 from '../../images/icons/icon96.png'
import icon97 from '../../images/icons/icon97.png'
import icon98 from '../../images/icons/icon98.png'
import icon99 from '../../images/icons/icon99.png'
import icon100 from '../../images/icons/icon100.png'

const icons = { icon1, icon2, icon3, icon4, icon5, icon6, icon7, icon8, icon9, icon10, icon11, icon12, icon13, icon14, icon15, icon16, icon17, icon18, icon19, icon20, icon21, icon22, icon23, icon24, icon25, icon26, icon27, icon28, icon29, icon30, icon31, icon32, icon33, icon34, icon35, icon36, icon37, icon38, icon39, icon40, icon41, icon42, icon43, icon44, icon45, icon46, icon47, icon48, icon49, icon50, icon51, icon52, icon53, icon54, icon55, icon56, icon57, icon58, icon59, icon60, icon61, icon62, icon63, icon64, icon65, icon66, icon67, icon68, icon69, icon70, icon71, icon72, icon73, icon74, icon75, icon76, icon77, icon78, icon79, icon80, icon81, icon82, icon83, icon84, icon85, icon86, icon87, icon88, icon89, icon90, icon91, icon92, icon93, icon94, icon95, icon96, icon97, icon98, icon99, icon100 } as const

export default function Page({ searchParams }: any) {
  // Only one icon is rendered, and no placeholder="blur" is used anywhere,
  // yet every imported icon ships its blurDataURL in the client bundle.
  const name = 'icon1' as keyof typeof icons
  return <Image src={icons[name]} alt={name} />
}
