import type { Metadata } from "next";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Suspense fallback={null}>
          <BodyContent>{children}</BodyContent>
        </Suspense>
      </body>
    </html>
  );
}

const BodyContent = async ({ children }: { children: React.ReactNode }) => {
  // await new Promise((resolve) => setTimeout(resolve, 1000));
  return <div>{children}</div>;
}
