import Image from 'next/image'

// The images are generated by `node scripts/generate-images.mjs` into public/.
export default function Home() {
  return (
    <main>
      <Image src="/img-0.jpg" alt="example" width={4096} height={4096} sizes="100vw" />
    </main>
  )
}
