export default function Home() {
  return (
    <main>
      <h1>Next.js Turbopack build-memory reproduction</h1>
      <p>The synthetic routes are generated by scripts/generate.mjs.</p>
    </main>
  );
}
